name: Build/release

on: push

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Set electron-builder args
        if: ${{ ! startsWith(github.ref, 'refs/tags/v') }}
        run: echo "EB_ARGS=--publish=never" >> $GITHUB_ENV

      - name: Build/release Electron app
        uses: samuelmeuli/action-electron-builder@v1
        with:
          args: ${{ env.EB_ARGS }}
          # GitHub token, automatically provided to the action
          # (No need to define this secret in the repo settings)
          github_token: ${{ secrets.github_token }}
          # If the commit is tagged with a version (e.g. "v1.0.0"),
          # release the app after building
          release: ${{ startsWith(github.ref, 'refs/tags/v') }}
